# Generated by Django 4.2.3 on 2023-07-17 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Toy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
                ("image_url", models.URLField()),
                (
                    "age_restriction",
                    models.CharField(
                        choices=[
                            ("3+", "3+"),
                            ("6+", "6+"),
                            ("8-12", "8-12"),
                            ("16", "16"),
                            ("18+", "18+"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ToyVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(max_length=50)),
                ("support_type", models.CharField(max_length=50)),
                (
                    "toy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="toys.toy"
                    ),
                ),
            ],
        ),
    ]
